### ISSUE TITLE
Don’t show “interlinked pages” section if none exist

### ISSUE THREAD

**Issue by remiliacorp** [remiliacorp/exocore#2]
Currently shows "Interlinked Pages There are no pages linking back to this one.", should simply be hidden entirely

**Comment by angel-faye** [comment]
Hello,

The issue here lies in /exocore/pages/articles.html (+journal.html, latest.html etc). This can be fixed with a simple check of the backlinks length before rendering the backlinks section, like so:

```
        {% if item.backlinks.length() > 0 %}
          <hr>
          <div class="backlinks-container">
            <side>
              <h1>Interlinked Pages</h1>
                <div class="backlinks-title">
                  {% for backlink in item.backlinks %}
                  {% assign linked_doc = site.documents | where: "url", backlink.url | first %}
                  <a href="{{backlink.url}}""><div class="backlink-box"><b>{{ linked_doc.title }}</b> — {{ linked_doc.collection | capitalize }}  <br>
                    <div class ="backlinks-excerpt">
                      {{ linked_doc.excerpt | strip_html | truncatewords: 20 }}
                    </div>
                  </a>
                </div>
                {% else %}
                <p>There are no pages linking back to this one. </p>
                {% endfor %}
            </side>
          </div>
          {% endif %}
```

Instead of:

```
        <hr>
          <div class="backlinks-container">
            <side>
              <h1>Interlinked Pages</h1>
                <div class="backlinks-title">
                  {% for backlink in item.backlinks %}
                  {% assign linked_doc = site.documents | where: "url", backlink.url | first %}
                  <a href="{{backlink.url}}""><div class="backlink-box"><b>{{ linked_doc.title }}</b> — {{ linked_doc.collection | capitalize }}  <br>
                    <div class ="backlinks-excerpt">
                      {{ linked_doc.excerpt | strip_html | truncatewords: 20 }}
                    </div>
                  </a>
                </div>
                {% else %}
                <p>There are no pages linking back to this one. </p>
                {% endfor %}
            </side>
          </div>
```

The same fix must also be done to the backlinks.html template in /exocore/_includes.

Hope this helps!

**Comment by hot-domme** [comment]
FIXED:

Only significant change I made to the above code was to remove the now-redundant 'no pages linking back' section, and rather than `{% if item.backlinks.length() > 0 %}`, i used `{% if item.backlinks.size > 0 %}`.

I also added `{% unless linked_doc.url == {{ baseurl }} %}` to ensure that links from the homepage are not counted as backlinks, since they show up as hyperlinks without a title.

**Comment by hot-domme** [comment]
Hey @angel-faye to embed these tweets did you use a plugin that is not already in the exocore? or did i add this function and forget about it?

![Screen Shot 2022-10-22 at 10 52 50 pm](https://user-images.githubusercontent.com/74973526/197337510-b0911c51-3de7-4ba1-8705-f1b75212759c.png)

**Comment by angel-faye** [comment]
Hi @hot-domme, i think I just copy pasted the twitter embed html into the .md file myself and it seemed to work
