### ISSUE TITLE
When a note is embedded, it should be truncated 

### ISSUE THREAD

**Issue by remiliacorp** [remiliacorp/exocore#5]
When a note is embedded, it should be truncated with a button to reveal the whole thing in line or navigate to that page

**Comment by hot-domme** [comment]
ADDED — tried two types of truncation: ellipsis and fade. They're done straight from the CSS.

they look like this:

<img width="1069" alt="ellipsis-truncate" src="https://user-images.githubusercontent.com/74973526/198162711-ab9f0350-bc21-45be-b5f0-dab11878acae.png">

<img width="1069" alt="fade-truncate" src="https://user-images.githubusercontent.com/74973526/198162699-fffe8d4b-6638-44e9-8426-fa9fecb1a093.png">

I've gone with fade for now, and the truncation is at 15 lines. 

To reveal inline i think i would need to edit the embed plugin itself (which also provides wikilinks). To edit a plugin we basically just copy it and insert it locally in the plugins folder, rather than calling it server-side. This comes with a lot of pros and cons, and I might do it later for a few plugins that are not well-maintained, but there's more important things for now.

note to self, in case i need to change truncation later:

https://css-tricks.com/line-clampin/

https://css-tricks.com/recreating-mdns-truncated-text-effect/
