### ISSUE TITLE
Table of contents only show up if there are at least 3 levels of header

### ISSUE THREAD

**Issue by remiliacorp** [remiliacorp/exocore#6]
Table of contents only show up if there are at least 3 levels of header for some reason, ignores if theres only 2 (# and ##)

**Comment by hot-domme** [comment]
FIXED(?)

TOC now shows up if there is a h2 —  i think this problem is from when i tried to make it so that TOC only appears if nested headers are present, which i achieved by making it appear only if there are h3s. All documents have an h1 from the title automatically, so if TOC appears for h1s there will be an empty TOC for all 
posts. 


So, I've made it appear provided there is a h2— only problem is, now when there is only 1 h2 in a document you get instances like this, which look ugly:  

<img width="836" alt="Screen Shot 2022-10-26 at 2 41 23 pm" src="https://user-images.githubusercontent.com/74973526/197929416-0121eb6f-2057-4a2d-8761-35ba9b206148.png">

Not sure how this can be fixed, since there are some cases where a user might want a TOC for a small number of headings, and some where they would not.

Could put `TOC: true` as default in front matter?
